#!/bin/bash

# create github repos from a list

if [ -f project.source ] ; then
  source project.source
fi

if ! [ -f $1 ] ; then
  echo "Error, missing $1 file"
  exit 2
fi

if ! [ x$2 == "xfree"  -o  x$2 == "xnonfree" -o x$2 == "xcuda" ] ; then
  echo "Error, need to be in free or nonfree section"
  exit 2
else
  section=$2
fi

for package in $(cat $1) ; do
  gh repo create -d "${package} - ${section}" --homepage "http://rpmfusion.org/Package/${package}" --disable-issues --disable-wiki  --public -t  packager rpmfusion/${package}
done
