#!/bin/bash
#
# mashism-el
#

if [ x${HOSTNAME} != "xbodhi-backend01.online.rpmfusion.net" ] ; then
        echo "$0: Wrong host: run on bodhi-backend01" && exit 2
fi

if [ getent group sysadmin-build $(id -nu) &>/dev/null ] ; then
	echo "$0: You need to be in the sysadmin-build group to run this" && exit 4
fi

if [ ! $(id -ng) == "sysadmin-build" ] ; then
  exec sg sysadmin-build $0
fi

# fix for rfbz#2142
export LANG=en_US.UTF-8
#DEBUG=1>/dev/null

umask 002

for n in free nonfree ; do
if [ -d /var/tmp/rpmfusion-${n}-comps ] ; then
  pushd /var/tmp/rpmfusion-${n}-comps &>/dev/null
    git remote update
    git reset origin/master --hard
    make
  popd &>/dev/null
else
  pushd /var/tmp &>/dev/null
    git clone https://github.com/rpmfusion-infra/rpmfusion-${n}-comps
    pushd rpmfusion-${n}-comps &>/dev/null
      make
    popd &>/dev/null
  popd &>/dev/null
fi
  for r in 8 9 10 ; do
    sg sysadmin-build "mash -o /mnt/koji/mash-${USER}/${n} -c /etc/mash/mash.${n}.conf  el${r} -f /var/tmp/rpmfusion-${n}-comps/comps-el${r}.xml $DEBUG"
    sg sysadmin-build "mash -o /mnt/koji/mash-${USER}/${n} -c /etc/mash/mash.${n}.conf  el${r}-testing -f /var/tmp/rpmfusion-${n}-comps/comps-el${r}.xml $DEBUG"
  done
done

