#!/bin/bash
#
# rpmfusion_sync
#
if [ x${HOSTNAME} != "xbodhi-backend01.online.rpmfusion.net" ] ; then
        echo "Wrong host: run on bodhi-backend01" && exit 1
fi

umask 002

FEDORA_STABLES="42 43 44"
#FEDORA_BRANCH="44"
FEDORA_RAWHIDE="45"

for i in free nonfree ; do
  for j in ${FEDORA_STABLES} ${FEDORA_BRANCH} ${FEDORA_RAWHIDE}; do
    sg sysadmin-build "mkdir -p /pub/${i}/fedora/tainted/${j}/"
    sg sysadmin-build "rsync -avHO --no-p /mnt/koji/mash-${USER}/${i}/${j}-tainted/* /pub/${i}/fedora/tainted/${j}/ --delete | grep -v -e repodata -e repoview"
  done
done
