#!/bin/bash

# rpmfusion-old-sign

echo Fedora free 31
find /mnt/koji/mash/free/31-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=C481937A
echo Fedora free 32
find /mnt/koji/mash/free/32-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=7BDA98EF593050A34B1697ABA0EE9D83100BCD92
echo Fedora free 33
find /mnt/koji/mash/free/33-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=D651FF2E
echo Fedora free 34
find /mnt/koji/mash/free/34-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=D651FF2E
echo Fedora nonfree 31
find /mnt/koji/mash/nonfree/31-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=54A86092
echo Fedora nonfree 32
find /mnt/koji/mash/nonfree/32-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=FE5A9393CB6E271B5A90CC1B0D9A76996DC1BE18
echo Fedora nonfree 33
find /mnt/koji/mash/nonfree/33-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=94843C65
echo Fedora nonfree 34
find /mnt/koji/mash/nonfree/34-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=94843C65
echo EL free 6
find /mnt/koji/mash/free/el6-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=849C449F
echo EL free 7
find /mnt/koji/mash/free/el7-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=F5CF6C1E
echo EL free 8
find /mnt/koji/mash/free/el8-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=158B3811
echo EL nonfree 6
find /mnt/koji/mash/nonfree/el6-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=5568BBB2
echo EL nonfree 7
find /mnt/koji/mash/nonfree/el7-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=A3108F6C
echo EL nonfree 8
find /mnt/koji/mash/nonfree/el8-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=BDDA8475

FEDORA_STABLES="31 32 33"
FEDORA_BRANCH=""
FEDORA_RAWHIDE="34"
EL_STABLES="6 7 8"

for f in free nonfree ; do
  for r in ${FEDORA_STABLES} ${FEDORA_BRANCH} ${FEDORA_RAWHIDE} ; do
    find /mnt/koji/mash/${f}/${r}-updates-candidate -name "*.rpm" | xargs -r koji-rpmfusion import-sig --write
  done
  for r in ${EL_STABLES} ; do
    find /mnt/koji/mash/${f}/el${r}-candidate -name "*.rpm" | xargs -r koji-rpmfusion import-sig --write
  done
done

