#!/bin/bash

# rpmfusion-repocheck

base_dir=/mnt/koji/mash

for f in free nonfree; do
  for v in 28-updates-testing 27-updates 26-updates 27-updates-testing 26-updates-testing 26-updates-testing ; do
    for a in armhfp i386 x86_64 aarch64 ppc64 ppc64le ; do
      [ -f ${base_dir}/${f}/${v}/${a}/repodata/repomd.xml ] || echo "failed ${v}/${a} for $f"
    done
  done
done

