#!/bin/bash

# rpmfusion-keep-latest

for f in free nonfree ; do
  for r in 41 42; do
    koji-keep-latest f${r}-${f}-updates-candidate
  done
  for r in 8 9 ; do
   koji-keep-latest el${r}-${f}-candidate
  done
    koji-keep-latest rawhide-${f}
done
