#!/bin/bash
#
# rpmfusion-post-sign
# 

FEDORA_STABLES="41 42 43"
FEDORA_BRANCH=""
FEDORA_RAWHIDE="44"
EL_STABLES="8 9 10"
EL_NEXT="10"

#Create report
rpmfusion-update-report | mail -r noreply@rpmfusion.org -s "RPM Fusion update report $(date -I)" rpmfusion-developers@lists.rpmfusion.org,rpmfusion-users@lists.rpmfusion.org

for f in free nonfree ; do
  for r in ${FEDORA_STABLES} ${FEDORA_BRANCH} ; do
    # Only in nonfree
    if [ $f == "nonfree" ] ; then
      koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}' |grep nvidia |grep -v 340xx |grep -v 390xx |grep -v 470xx |grep -v 580xx |grep -v open-kmod | xargs -r koji-rpmfusion tag-build f${r}-${f}-nvidia-driver
      koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}' |grep  nvidia-open-kmod | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-testing f${r}-${f}-tainted
      koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}' |grep  steam | xargs -r koji-rpmfusion tag-build f${r}-${f}-steam
      #automove discord to stable ASAP
      koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}' | grep discord | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-candidate f${r}-${f}-updates
    # Only in free
    elif [ $f == "free" ] ; then
      # libdvdcss in tainted free
      koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}' |grep  libdvdcss| xargs -r koji-rpmfusion move-build f${r}-${f}-updates-testing f${r}-${f}-tainted
      #automove freeworld to stable ASAP
      koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}' | grep freeworld | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-candidate f${r}-${f}-updates
    fi
    # Common to free/nonfree
    #
    # Adapt target for branch
    if [ x${r} == x${FEDORA_BRANCH} ] ; then
       _updates=""
    else
       _updates="-updates"
    fi
    koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}' |grep -v release | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-testing f${r}-${f}${_updates}
    koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-candidate f${r}-${f}-updates-testing
  done
  for r in ${FEDORA_RAWHIDE} ; do
    if [ $f == "nonfree" ] ; then
      koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}' |grep nvidia | grep -v 340xx |grep -v 390xx |grep -v 470xx |grep -v 580xx |grep -v open-kmod | xargs -r koji-rpmfusion tag-build f${r}-${f}-nvidia-driver
      koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}' |grep  nvidia-open-kmod | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-candidate f${r}-${f}-tainted
      koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}' |grep  steam | xargs -r koji-rpmfusion tag-build f${r}-${f}-steam
    fi
    koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-candidate f${r}-${f}
  done
  for r in ${EL_STABLES} ; do
    koji-rpmfusion list-tagged el${r}-${f}-testing --quiet | awk '{print $1}' | grep libdvdcss |xargs -r koji-rpmfusion move-build el${r}-${f}-testing el${r}-${f}-tainted
    koji-rpmfusion list-tagged el${r}-${f}-testing --quiet | awk '{print $1}' |grep  nvidia-open-kmod | xargs -r koji-rpmfusion move-build el${r}-${f}-testing el${r}-${f}-tainted
    #automove discord to stable ASAP
    koji-rpmfusion list-tagged el${r}-${f}-candidate --quiet | awk '{print $1}' | grep discord | xargs -r koji-rpmfusion move-build el${r}-${f}-candidate el${r}-${f}
    koji-rpmfusion list-tagged el${r}-${f}-testing --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build el${r}-${f}-testing el${r}-${f}
    koji-rpmfusion list-tagged el${r}-${f}-candidate --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build el${r}-${f}-candidate el${r}-${f}-testing
  done
  for r in ${EL_NEXT} ; do
    koji-rpmfusion list-tagged el${r}-next-${f}-testing --quiet | awk '{print $1}' | grep libdvdcss |xargs -r koji-rpmfusion move-build el${r}-next-${f}-testing el${r}-${f}-tainted
    koji-rpmfusion list-tagged el${r}-next-${f}-testing --quiet | awk '{print $1}' |grep  nvidia-open-kmod | xargs -r koji-rpmfusion move-build el${r}-next-${f}-testing el${r}-${f}-tainted
    #automove discord to stable ASAP
    koji-rpmfusion list-tagged el${r}-next-${f}-candidate --quiet | awk '{print $1}' | grep discord | xargs -r koji-rpmfusion move-build el${r}-next-${f}-candidate el${r}-next-${f}
    koji-rpmfusion list-tagged el${r}-next-${f}-testing --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build el${r}-next-${f}-testing el${r}-next-${f}
    koji-rpmfusion list-tagged el${r}-next-${f}-candidate --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build el${r}-next-${f}-candidate el${r}-next-${f}-testing
  done
done
