#!/bin/bash
#
# rpmfusion_sync
#
if [ x${HOSTNAME} != "xbodhi-backend01.online.rpmfusion.net" ] ; then
        echo "Wrong host: run on bodhi-backend01" && exit 1
fi

umask 002

FEDORA_STABLES="42 43 44"
#FEDORA_BRANCH="44"

for i in free nonfree ; do
  sg sysadmin-build "rsync -avHO --no-p --delete /mnt/koji/mash-${USER}/${i}/rawhide/* /pub/${i}/fedora/development/rawhide/Everything | grep -v -e repodata -e repoview"
  #j=44
  for j in ${FEDORA_BRANCH}; do
    sg sysadmin-build "rsync -avHO --no-p --delete /mnt/koji/mash-${USER}/${i}/${j}-branch/* /pub/${i}/fedora/development/${j}/Everything | grep -v -e repodata -e repoview"
    sg sysadmin-build "rsync -avHO --no-p /mnt/koji/mash-${USER}/${i}/${j}-updates-testing/* /pub/${i}/fedora/updates/testing/${j}/ --delete | grep -v -e repodata -e repoview"
  done
  for j in ${FEDORA_STABLES}; do
    sg sysadmin-build "rsync -avHO --no-p /mnt/koji/mash-${USER}/${i}/${j}-updates-testing/* /pub/${i}/fedora/updates/testing/${j}/ --delete | grep -v -e repodata -e repoview"
    sg sysadmin-build "rsync -avHO --no-p /mnt/koji/mash-${USER}/${i}/${j}-updates/* /pub/${i}/fedora/updates/${j}/ --delete | grep -v -e repodata -e repoview"
  done
done
