#!/bin/bash

# rpmfusion-sign

FEDORAS="41 42 43"
BRANCHED=""
RAWHIDE="44"
ELS="8 9 10"
NEXT="10"
SIGUL_VERBOSE=" --gpg-agent --sigul-batch-size 1 -v "

_sigul_sign() {
local _sigul_tag=$1
local _sigul_key=$2
rm -f /tmp/sigul-${_sigul_tag}.log
koji-rpmfusion list-tagged ${_sigul_tag} --quiet | awk '{print $1}' | tee /tmp/sigul-${_sigul_tag}.log
local _sigul_list=$(cat /tmp/sigul-${_sigul_tag}.log 2>/dev/null| wc -l)
if [ x${_sigul_list} != x0 ] ; then
  sigulsign_unsigned.py --tag ${_sigul_tag} --arch koji-rpmfusion ${_sigul_key} ${SIGUL_VERBOSE}
fi
}

for j in free nonfree ; do
  for i in ${FEDORAS} ${BRANCHED} ${RAWHIDE}; do
    kn=$i
    if [ $i -ge 33 ] ; then
	    kn=2020
    fi
    echo "------------------"
    echo "Fedora ${i} - ${j}"
    echo "------------------"
    _sigul_sign f${i}-${j}-updates-candidate rpmfusion-fedora-${j}-${kn}
  done

  for i in ${ELS} ; do
    echo "------------------"
    echo "EL ${i} - ${j}"
    echo "------------------"
    _sigul_sign el${i}-${j}-candidate rpmfusion-el-${j}-${i}
  done
  for i in ${NEXT} ; do
    echo "------------------"
    echo "NEXT ${i} - ${j}"
    echo "------------------"
    _sigul_sign el${i}-next-${j}-candidate rpmfusion-el-${j}-${i}
  done

done

for i in ${FEDORAS} ${BRANCHED} ${RAWHIDE} ; do
    kn=$i
    if [ $i -ge 33 ] ; then
	    kn=2020
    fi
  # Sign CUDA namespace
  echo "------------------"
  echo "Fedora ${i} - CUDA"
  echo "------------------"
  _sigul_sign f${i}-cuda-candidate rpmfusion-cuda-2019
done
