#!/bin/bash
#
# rpmfusion_sync
#
if [ x${HOSTNAME} != "xbodhi-backend01.online.rpmfusion.net" ] ; then
        echo "Wrong host: run on bodhi-backend01" && exit 1
fi

umask 002

for i in nonfree ; do
  for j in 38 39 40 41; do
    sg sysadmin-build "mkdir -p /pub/${i}/fedora/steam/${j}/ "
    sg sysadmin-build "rsync -avHO --no-p /mnt/koji/mash/${i}/${j}-steam/* /pub/${i}/fedora/steam/${j}/ --delete | grep -v -e repodata -e repoview"
  done
done
