#!/bin/bash

# update-appstream

for i in free nonfree ; do
  for f in rawhide ; do
    pushd /pub/${i}/fedora/development/${f}/Everything &>/dev/null
      appstream-builder --origin=rpmfusion.org --basename=appstream --cache-dir=/tmp/asb-cache --enable-hidpi --min-icon-size=32 --output-dir=/tmp/asb-md --packages-dir=x86_64/os/ --temp-dir=/tmp/asb-icons
      [ -e /tmp/asb-md/appstream-icons.tar.gz ] && modifyrepo_c --no-compress --simple-md-filenames /tmp/asb-md/appstream-icons.tar.gz x86_64/os/repodata/
      [ -e /tmp/asb-md/appstream-ignore.xml.gz ] && modifyrepo_c --no-compress --simple-md-filenames /tmp/asb-md/appstream-ignore.xml.gz x86_64/os/repodata/
      [ -e /tmp/asb-md/appstream-screenshots.tar.gz ] && modifyrepo_c --no-compress --simple-md-filenames /tmp/asb-md/appstream-screenshots.tar.gz x86_64/os/repodata/
      modifyrepo_c --no-compress --simple-md-filenames /tmp/asb-md/appstream.xml.gz x86_64/os/repodata/
      rm -rf /tmp/asb-md
    popd &>/dev/null
  done
done

