#!/bin/bash

# rpmfusion-updates-report


FEDORAS="42 43"
FEDORA_BRANCH="44"
FEDORA_RAWHIDE="45"
CUDA="41"
ELS="8 9 10"
NEXT="10"

echo "RPM Fusion update report"
echo "------------------------"
echo ""
for f in free nonfree ; do
echo "Section $f:"
echo "-------------"
  for r in ${FEDORAS} ${FEDORA_BRANCH}; do
    echo "Fedora $r"
    echo "-------------"
    echo "Pushed to testing: "
    koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}'
    echo ""
    echo "Pushed to stable: "
    koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}'
    echo ""
  done
  echo ""
  for r in ${ELS} ; do
    echo "EL $r"
    echo "-------------"
    echo "Pushed to testing: "
    koji-rpmfusion list-tagged el${r}-${f}-candidate --quiet | awk '{print $1}'
    echo ""
    echo "Pushed to stable: "
    koji-rpmfusion list-tagged el${r}-${f}-testing --quiet | awk '{print $1}'
    echo ""
  done
  for r in ${NEXT} ; do
    echo "EL $r Next"
    echo "-------------"
    echo "Pushed to testing: "
    koji-rpmfusion list-tagged el${r}-next-${f}-candidate --quiet | awk '{print $1}'
    echo ""
    echo "Pushed to stable: "
    koji-rpmfusion list-tagged el${r}-next-${f}-testing --quiet | awk '{print $1}'
    echo ""
  done
done
echo ""
echo "Theses packages will be available in main mirror in a few hours. Wait for local mirrors to sync"
echo "Please report any issue to https://bugzilla.rpmfusion.org"
echo ""

