#!/bin/bash

# rpmfusion-old-sign

echo Fedora free 34
find /mnt/koji/mash/free/34-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=D651FF2E
echo Fedora free 35
find /mnt/koji/mash/free/35-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=D651FF2E
echo Fedora free 36
find /mnt/koji/mash/free/36-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=D651FF2E
echo Fedora nonfree 34
find /mnt/koji/mash/nonfree/34-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=94843C65
echo Fedora nonfree 35
find /mnt/koji/mash/nonfree/35-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=94843C65
echo Fedora nonfree 36
find /mnt/koji/mash/nonfree/36-updates-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=94843C65
echo EL free 7
find /mnt/koji/mash/free/el7-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=F5CF6C1E
echo EL free 8
find /mnt/koji/mash/free/el8-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=158B3811
echo EL nonfree 7
find /mnt/koji/mash/nonfree/el7-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=A3108F6C
echo EL nonfree 8
find /mnt/koji/mash/nonfree/el8-candidate -name "${1}*.rpm" | xargs -r rpmsign --resign -key-id=BDDA8475

FEDORA_STABLES="34 35"
FEDORA_BRANCH=""
FEDORA_RAWHIDE="36"
EL_STABLES="7 8"

for f in free nonfree ; do
  for r in ${FEDORA_STABLES} ${FEDORA_BRANCH} ${FEDORA_RAWHIDE} ; do
    find /mnt/koji/mash/${f}/${r}-updates-candidate -name "*.rpm" | xargs -r koji-rpmfusion import-sig --write
  done
  for r in ${EL_STABLES} ; do
    find /mnt/koji/mash/${f}/el${r}-candidate -name "*.rpm" | xargs -r koji-rpmfusion import-sig --write
  done
done

