#!/bin/bash

# rpmfusion-pre-sign

umask 002


# call rpmfusion-keep-latest to avoid any older build
rpmfusion-keep-latest

# bodhi01
for f in free nonfree ; do
  for r in 33 34 35; do
    sg sysadmin-build "mash -o /mnt/koji/mash/${f} -c /etc/mash/mash.${f}.conf  ${r}-updates-candidate"
  done
done

# bodhi01
for f in free nonfree ; do
  for r in 7 8 ; do
    sg sysadmin-build "mash -o /mnt/koji/mash/${f} -c /etc/mash/mash.${f}.conf  el${r}-candidate"
  done
done

