#!/bin/bash
#
# rpmfusion-post-sign
# 

FEDORA_STABLES="27 28"
FEDORA_BRANCH="29"
EL_STABLES="6 7"

for f in free nonfree ; do
  for r in ${FEDORA_STABLES} ${FEDORA_BRANCH} ; do
    find /mnt/koji/mash/${f}/${r}-updates-candidate -name "*.rpm" | xargs -r koji-rpmfusion import-sig --write
  done
  for r in ${EL_STABLES} ; do
    find /mnt/koji/mash/${f}/el${r}-candidate -name "*.rpm" | xargs -r koji-rpmfusion import-sig --write
  done
done

#Create report
rpmfusion-update-report | mail -r noreply@rpmfusion.org -s "RPM Fusion update report $(date -I)" rpmfusion-developers@lists.rpmfusion.org,rpmfusion-users@lists.rpmfusion.org

for f in free nonfree ; do
  for r in ${FEDORA_STABLES} ${FEDORA_BRANCH} ; do
    koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}' |grep nvidia |grep -v nvidia-340xx |grep -v nvidia-390xx | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-testing f${r}-${f}-tainted
    koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}' |grep  libdvdcss| xargs -r koji-rpmfusion move-build f${r}-${f}-updates-testing f${r}-${f}-tainted
    koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}' |grep -v chromium-freeworld|grep -v nvidia| xargs -r koji-rpmfusion move-build f${r}-${f}-updates-testing f${r}-${f}-updates
    koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-candidate f${r}-${f}-updates-testing
  done
  for r in ${EL_STABLES} ; do
    koji-rpmfusion list-tagged el${r}-${f}-testing --quiet | awk '{print $1}' | grep libdvdcss |xargs -r koji-rpmfusion move-build el${r}-${f}-testing el${r}-${f}-tainted
    koji-rpmfusion list-tagged el${r}-${f}-testing --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build el${r}-${f}-testing el${r}-${f}
    koji-rpmfusion list-tagged el${r}-${f}-candidate --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build el${r}-${f}-candidate el${r}-${f}-testing
  done

done

