#!/bin/bash

# rpmfusion-pre-sign

umask 002

# bodhi01
for f in free nonfree ; do
  for r in 26 27 28 ; do
    sg sysadmin-build "mash -o /mnt/koji/mash/${f} -c /etc/mash/mash.${f}.conf  ${r}-updates-candidate"
  done
done

# bodhi01
for f in free nonfree ; do
  for r in 6 7 ; do
    sg sysadmin-build "mash -o /mnt/koji/mash/${f} -c /etc/mash/mash.${f}.conf  el${r}-candidate"
  done
done

