#!/bin/bash
#
# rpmfusion-post-sign
# 

for f in free nonfree ; do
  for r in 25 26 27 ; do
    find /mnt/koji/mash/${f}/${r}-updates-candidate -name "*.rpm" | xargs -r koji-rpmfusion import-sig --write
  done
  for r in 6 7 ; do
    find /mnt/koji/mash/${f}/el${r}-candidate -name "*.rpm" | xargs -r koji-rpmfusion import-sig --write
  done
done

#Create report
./rpmfusion-update-report | mail -r noreply@rpmfusion.org -s "RPM Fusion update report $(date -I)" rpmfusion-developers@lists.rpmfusion.org,rpmfusion-users@lists.rpmfusion.org

for f in free nonfree ; do
  for r in 25 26 ; do
    koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}' |grep -v nvidia | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-testing f${r}-${f}-updates
    koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-candidate f${r}-${f}-updates-testing
  done
  for r in 27 ; do
    koji-rpmfusion list-tagged f${r}-${f}-updates-testing --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-testing f${r}-${f}
    koji-rpmfusion list-tagged f${r}-${f}-updates-candidate --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build f${r}-${f}-updates-candidate f${r}-${f}-updates-testing
  done
  for r in 6 7 ; do
    koji-rpmfusion list-tagged el${r}-${f}-testing --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build el${r}-${f}-testing el${r}-${f}
    koji-rpmfusion list-tagged el${r}-${f}-candidate --quiet | awk '{print $1}' | xargs -r koji-rpmfusion move-build el${r}-${f}-candidate el${r}-${f}-testing
  done

done

